IO5PIZZA-26 organize components imports
krzysiou/ohio-pizza pull request #15
Opened 2023-04-23 16:45 UTC by Matiixx

2023-04-24 11:53 UTC, krzysiou requested changes

2023-04-24 11:53 UTC, krzysiou commented on src/components/pages/index.ts
> +export * from './NotFound/NotFound';
I would add a newline after this line

2023-04-24 11:55 UTC, krzysiou requested changes

2023-04-24 11:55 UTC, krzysiou commented on src/components/common/index.ts
> +export * from './navbar/Navbar';
Here aswell

2023-04-24 14:07 UTC, Matiixx commented
I've add newlines

2023-04-25 18:28 UTC, krzysiou approved these changes

2023-04-25 18:28 UTC, merged